spring.application.name=pet_wearable
server.port=8085

mqtt.broker=tcp://${MQTT_HOST:localhost}:${MQTT_PORT:1883}
mqtt.client-id=pet-wearable-client
mqtt.topic=pet/vitals

gateway.url=http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8888}