spring.application.name=pet_wearable
server.port=8085

mqtt.broker=tcp://${MQTT_HOST:localhost}:${MQTT_PORT:1883}
mqtt.client-id=pet-wearable-client
mqtt.topic=pet/vitals

gateway.url=http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8888}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}
spring.security.oauth2.client.registration.pet-wearable.client-id=pet-wearable-service
spring.security.oauth2.client.registration.pet-wearable.client-secret=${KEYCLOAK_CLIENT_SECRET:cJmrhLBTXL2g9oZlfdjVMVQ2eycb3dmY}
spring.security.oauth2.client.registration.pet-wearable.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.pet-wearable.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}