spring.application.name=pet_wearable

mqtt.broker=tcp://localhost:1883
mqtt.client-id=pet-wearable-client
mqtt.topic=pet/vitals

thresholds.heart-rate-max=200
thresholds.heart-rate-min=30
thresholds.respiration-max=40
thresholds.respiration-min=10
